CREATE TABLE links (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       original_url VARCHAR(2048) NOT NULL,
                       short_code VARCHAR(12) NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,

                       CONSTRAINT uk_links_short_code UNIQUE (short_code)
);